# Generated by Django 6.0.2 on 2026-02-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_released_to_landlord_agentcommission_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalApplication',
            new_name='Application',
        ),
    ]
